### ISSUE TITLE
New SmellType: Long Method

### ISSUE THREAD

**Issue by mastodonfarm** [QualInsight/qualinsight-plugins-sonarqube-smell#46]
This comes from Coding Horror's list of smells.

I find myself often choosing either MULTIPLE_RESPONSIBILITIES or simply BAD_DESIGN to express what I think is simply a "long method" smell.

**Comment by pawlakm** [comment]
Hi,

Thanks for your feedback. Question: why aren't you using SQ's Java plugin to report these long methods automatically ?

See [squid:S138](https://sonarqube.com/coding_rules#q="Methods%20should%20not%20have%20too%20many%20lines"|languages=java)

**Comment by pawlakm** [comment]
Hi,

Did you have time to check the link I posted ?

M.

**Comment by pawlakm** [comment]
As I got no answer, I'm closing this issue.
