### ISSUE TITLE
New SmellType: Conditional Complexity

### ISSUE THREAD

**Issue by mastodonfarm** [QualInsight/qualinsight-plugins-sonarqube-smell#47]
This comes from Coding Horror's list.

Annotating switches, long if/else if/... chains or methods and classes with high cyclomatic complexity would be nice.

**Comment by pawlakm** [comment]
Hi,

Is there a reason SQ's Java plugin [complexity rules](https://sonarqube.com/coding_rules#q="too%20complex"|languages=java) are not sufficient ? This plugin is meant to complete automatic checks with manual reviews.

**Comment by pawlakm** [comment]
Hi,

Did you have time to check the link I posted ?

M.

**Comment by pawlakm** [comment]
As I got no answer, I'm closing this issue.
