### ISSUE TITLE
New Code Smell Type proposal

### ISSUE THREAD

**Issue by charlesmorin** [QualInsight/qualinsight-plugins-sonarqube-smell#54]
As discussed in the Google group thread, please add the following smell types: 

- non compliance with team standard or convention (NOT_COMPLIANT_TO_STANDARD)
- missing mandatory test (MISSING_MANDATORY_TEST)
- missing mandatory javadoc (MISSING_MANDATORY_JAVADOC)
- catch all type (OTHER)

Thread URL:
https://groups.google.com/forum/#!topic/code-smells/F2X9fA2zmgM

Cheers

**Comment by pawlakm** [comment]
Hi Charles,

As further discussed by mail, I'll create the following types :

- NON_COMPLIANCE_WITH_STANDARDS
- MISSING_TEST
- MISSING_DOCUMENTATION
- OTHER

**Comment by pawlakm** [comment]
4.0.0-RC2-SNAPSHOT is working fine on latest LTS (with latest java plugin). Here is a screenshot of the widget:

![screen shot 2017-01-19 at 21 36 45](https://cloud.githubusercontent.com/assets/13068475/22124297/8864c79a-de8f-11e6-8257-6c1562b5630c.png)

**Comment by pawlakm** [comment]
Hi Charles,

To answer your question, version 4.0.0 is compatible with current LTS (5.6.x, tested with 5.6.4) and depends on java 4.4 plugin. See the [requirements](https://github.com/QualInsight/qualinsight-plugins-sonarqube-smell/tree/4.0.0#requirements-and-compatibility-matrix) part of the documentation.

Can you please check if you agree with the default [severity levels](https://github.com/QualInsight/qualinsight-plugins-sonarqube-smell/tree/4.0.0#available-smell-types) of the new smell types ?

Thanks in advance,

Michel

**Comment by pawlakm** [comment]
The plugin seems to work fine with SQ 6.2 as well. However, project dashboards having been removed by SonarSource, custom widget cannot be used anymore... Measure counting Code Smells reported by the plugin can however be seen in the "Measures" tab. It's better than nothing, but ways less readable than a pie diagram...

**Comment by charlesmorin** [comment]
I'm good with the default severity levels. Makes perfect sense to me.

Thank you

**Comment by pawlakm** [comment]
Great, I close this issue then. I'll create a new RC this evening after having finished working on #56.
